### ISSUE TITLE
Split Query Limitation

### ISSUE THREAD

**Issue by bala-drg** [implydata/plywood#165]
is there any limitation in the plywood query that only we can split upto 5 dimensions? I'm getting error if i add more that 5 in the split query. Please help

**Comment by bala-drg** [comment]
@vogievetsky any updates on above comment?

**Comment by prateek-vars** [comment]
Hey @bala-drg, could you confirm if this issue has been fixed or if there's any workaround available? I'd appreciate it if you could provide some assistance. Also tagging @vogievetsky and @jgoz for their input on this matter. Thanks!

**Comment by vogievetsky** [comment]
This is due to the `maxComputeCycles` parameter that defaults to `5`. It is passed as a second argument to the `compute` function (or as the second argument to the `basicExecutor`) and it could be called `maxNestedSplits` since every nested split will require a compute cycle. It is there to prevent accidentally issuing very heavy queries as the queries get exponentially more expensive as you add nested splits (and require more compute cycles). If you increase the `maxComputeCycles` you might also want to think about `maxQueries` and `maxRows` https://github.com/implydata/plywood/blob/f892b5d2d809500260c3b0a5a4783a94dbd33c25/src/expressions/baseExpression.ts#L116.
